services:
  Dbp\Relay\CoreConnectorTextfileBundle\Service\UserAttributeProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreConnectorTextfileBundle\Service\AuthorizationService:
    autowire: true
    autoconfigure: true